### ISSUE TITLE
Schedule and Cancel methods are not publicly available

### ISSUE THREAD

**Issue by soccerob** [distriqt/ANE-JobScheduler#1]
I don't see the public methods for scheduling and canceling the termination job.

![image](https://user-images.githubusercontent.com/151275/43872207-74a54d7e-9b4e-11e8-8810-65b3e7cbb9b4.png)

**Comment by marchbold** [comment]
They definitely are there, can you double check you have correctly added the ANE.

**Comment by rewb0rn** [comment]
It's the same here, they are not visible in FlashDevelop. But the application compiles and the termination works if you paste the code. If you open the JobScheduler class / stub the methods are not listed there as well. So it's more of an autocomplete / declaration problem but the ANE works fine.

**Comment by marchbold** [comment]
Let me double check, FlashDevelop uses the default implementation swc for autocomplete correct?

**Comment by rewb0rn** [comment]
I have directly referenced the .ane as an external library in the FlashDevelop project, so I think FlashDevelop uses the classes that are included in the swc inside the ane, but I am not sure.

**Comment by marchbold** [comment]
Yeah, there are multiple swc's inside an ANE. I believe FlashDevelop uses the default.

I'm going to rebuild the ANE and commit just to make sure the default lib was built correctly.

**Comment by soccerob** [comment]
Fixed! Thank you!
