### ISSUE TITLE
Solved: No such service ComponentInfo

### ISSUE THREAD

**Issue by soccerob** [distriqt/ANE-JobScheduler#2]
I'm not sure if I'm doing something incorrectly, I've wired in several of the distriqt extensions but I haven't seen this issue before. I tried this on 2 different Android 8.0 devices. 

**Error #2044: Unhandled error:. text=No such service ComponentInfo{air.com.spicerackmedia.bingoshowdown/com.distriqt.extension.jobscheduler.services.TerminateAppJobService}**

```
private function SomeClass() {
	try {
		JobScheduler.init( "" );
		trace( "JobScheduler.init() success" );
		trace("isSupported: " + JobScheduler.isSupported);
		trace("version: " + JobScheduler.VERSION);
	} catch (e:Error) {
		trace( "ERROR::"+e.message );
	}
}
private function onApplicationActivated(e:SpicerackEvent):void {
	var jobCanceled:Boolean = JobScheduler.instance.cancelTermination();
	trace("jobCanceled: " + jobCanceled);
}

private function onApplicationBackgrounded(e:SpicerackEvent):void {
	var jobScheduled:Boolean = JobScheduler.instance.scheduleTermination( 1000 * 7 );
	trace("jobScheduled: " + jobScheduled);
}
```

console output: 
_JobScheduler.init() success
isSupported: true
version: 0.0.011
#######onApplicationBackgrounded
jobScheduled: false
Error #2044: Unhandled error:. text=No such service ComponentInfo{air.com.spicerackmedia.bingoshowdown/com.distriqt.extension.jobscheduler.services.TerminateAppJobService}
#######onApplicationActivated
jobCanceled: true_

**Comment by soccerob** [comment]
Solved by adding the following to the application manifest:

```
<service				       
 android:name="com.distriqt.extension.jobscheduler.services.TerminateAppJobService"
                        android:permission="android.permission.BIND_JOB_SERVICE"
                        android:exported="true" />
```

**Comment by Elintondm** [comment]
Hi @soccerob,

Where did you put this in your manifest? Could you show a bigger part of your xml?

Thanks

**Comment by marchbold** [comment]
Have a look in the example for a complete listing:

https://github.com/distriqt/ANE-JobScheduler/blob/master/example/starling/src/TestJobScheduler-app.xml#L55-L70

**Comment by Elintondm** [comment]
Thanks
