### ISSUE TITLE
Compatibility with Notifications

### ISSUE THREAD

**Issue by Faketa** [distriqt/ANE-JobScheduler#3]
Hi, my app has been crashed after termination from JobScheduler and after receiving notification from Notifications. E.g. termination is set up for 5 minutes and notification is set up for 6 minutes after deactivate event and then after 6 minutes (app is in background) I get notification and after tap on it, app is starting and after few seconds it has been crashed.

- AIR SDK version: 30
- Device OS: Android

**Comment by marchbold** [comment]
Hi,

Can you post the logs from the device? 

What notification service are you using, is this a local or push notification?
